language: php
php:
    - "7.3.4"
# Comandos a serem executados antes do seu ambiente ser executado.

before_install:
    - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
    
 # Comandos que você deseja executar que verificarão sua compilação.

before_script:
    - composer install
script: phpunit --configuration phpunit.xml --coverage-text

notifications:
    email:
    - fbiemo@unilurio.ac.mz
    - sabaco@unilurio.ac.mz
    - raimundo.jose@unilurio.ac.mz
    - hofumane@unilurio.ac.mz
    - tlourei@unilurio.ac.mz
 
